api_url: "https://api.example.com"
headers:
  accept: "application/json"
  content-type: "application/json"
  x-api-key: "your-api-key"

payload:
  door_id: "your-door-id"
  user_id: "your-identifier"

#led_enabled: true
#led_pin: 23     
#button_pin: 17  