token_url: "https://api.example.com/token"
token_headers:
  accept: "application/json"
  x-api-key: "{{ api_key }}:"


api_url: "https://api.example.com"

payload:
  payload-1: "your-payload-data"
  payload-2: "your-payload-data"

#led_enabled: true
#led_pin: 23     
#button_pin: 17  