services:
  rondo-app:
    image: ghcr.io/thequib/rondo:latest
    container_name: rondo
    volumes:
      - ${PWD}/config.yml:/home/pi/rondo/config.yml
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    privileged: true