services:
  rondo-app:
    image: ghcr.io/thequib/rondo:latest
    container_name: rondo
    volumes:
      - /home/pi/rondo/config.yml:/app/config.yml
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    privileged: true