services:
  rondo-app:
    image: ghcr.io/thequib/rondo:latest
    container_name: rondo
    volumes:
      - ./config.yaml:/home/pi/rondo/config.yaml
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
    privileged: true