name: Build and Push Rondo image

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'Dockerfile'
      - '.github/workflows/deploy-container.yml'
      - 'docker-compose.yml'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm/v7,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm/v7,linux/arm64
          tags: |
            ghcr.io/thequib/rondo:latest
            ghcr.io/thequib/rondo:${{ github.sha }}