name: Build and Push Documentation Site

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'docs/**'

permissions:
  contents: read
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

env:
  HUGO_ENV: production
  HUGO_VERSION: "0.160.1"
  GO_VERSION: "1.26.2"

jobs:
  # Build job
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Install Hugo
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-arm64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Go
        run: |
          wget -O ${{ runner.temp }}/go.tar.gz https://dl.google.com/go/go${GO_VERSION}.linux-arm64.tar.gz \
          && sudo tar -C /usr/local -xzf ${{ runner.temp }}/go.tar.gz
          echo "/usr/local/go/bin" >> $GITHUB_PATH

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build site
        working-directory: docs
        run: hugo --minify --baseURL "https://thequib.github.io/Rondo/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./docs/public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04-arm
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5